"use client";

import { Inter } from "next/font/google";
import AdminMenu from "../../components/AdminMenu";
import StaffMenu from "../../components/StaffMenu";
import { usePathname } from 'next/navigation';
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <div className={inter.className}>
      {pathname.startsWith('/admin') ? (
        <AdminMenu />
      ) : pathname.startsWith('/staff') ? (
        <StaffMenu />
      ) : (
        /* Component menu default atau null jika tidak ada yang sesuai */
        <></>
      )}
      <main className="pt-5 max-w-5xl mx-auto px-6 md:px-12 xl:px-6">
        {children}
      </main>
    </div>
  );
}